import pandas as pd
import numpy

data = pd.read_csv('/home/ubuntu/environment/huntsman_scholar_final_proj/Results/Resource Needs Survey.csv')
data = data.drop(columns = ['RecipientLastName', 'RecipientFirstName', 'RecipientEmail','ResponseID', 'ResponseSet', 'IPAddress', 'StartDate', 'EndDate','LocationLatitude',
       'LocationLongitude', 'LocationAccuracy','ExternalDataReference', 'Finished', 'Status'])
data.drop([0,1], axis=0, inplace=True)
data['Department'] = data['Q4'].replace(['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','50','51','52','53','54','55','56','57','58','59','60','61','62','63','64','65','66','67','68','69','70','71','72','73','74','75','76','77','78','79','80'], ['Accounting','Military Science','Music','Nursing','Nutrition, Dietetics, and Food Sciences','Physics','Political Science','Psychology','Social Work','Sociology and Anthropology','Special Education and Rehabilitation Counseling','Teacher Education and Leadership','Theatre','Watershed Sciences','Wildland Sciences','World Languages and Cultures','Mathematics and Statistics','Airforce ROTC','Animal, Dairy and Veterinary Science','Applied Economics','Applied Sciences, Technology, and Education','Art','Aviation and Technical Education','Biological Engineering','Biology','Center for Anticipatory Intellignce','Chemistry and Biochemistry','Civil and Environmental Engineering','Communication Studies and Philosophy','Communicative Disorders and Deaf Education','Computer Science','Data Analytics & Information Systems','Economics anf Finance','Electrical and Cumputer Engineering','Engineering Education','English','Environment and Society','Geosciences','History','Human Development and Family Studies','Instructional Technology & Learning Sciences','Journalism','Kinesiology and Health Science','Landscape Architecture and Environmental Planning','Management','Marketing and Strategy','Mechanical and Aerospace Engineering','Exploratory'])
data['College'] = data['Q5'].replace(['1','2','3','4','5','6','7','8','9','10'], ['Caine College of the Arts','College of Agriculture and Applied Sciences','College of Engineering','College of Humanities and Social Sciences','College of Science','College of Veterinary Medicine','College of Education and Human Services','Huntsman School of Business','College of Natural Resources','Undeclared'])
print(data.columns)
print(data)

data.to_csv('/home/ubuntu/environment/huntsman_scholar_final_proj/Results/Resource_Needs_Edit.csv')